SELECT [E3TimeStamp], [MB2.QGFV_A.MED.IB], [MB2.QGFV_A.MED.IC], [MB2.QGFV_A.MED.VA], [MB2.QGFV_A.MED.VB], [MB2.QGFV_A.MED.VC], [MB2.QGFV_A.MED.I_Trif], 
[MB2.QGFV_A.MED.V_Trif], [MB2.QGFV_A.MED.PA], [MB2.QGFV_A.MED.PB], [MB2.QGFV_A.MED.PC], [MB2.QGFV_A.MED.FREQ]
FROM QGBT_A_MED
WHERE CAST(E3TimeStamp AS DATE) = '2023-06-05'
GO


SELECT [E3TimeStamp], [MB2.QGFV_A.DJ.VA], [MB2.QGFV_A.DJ.VB], [MB2.QGFV_A.DJ.VC],[MB2.QGFV_A.DJ.VAB],[MB2.QGFV_A.DJ.VBC],[MB2.QGFV_A.DJ.VCA]
FROM QGBT_A_CAB
WHERE CAST(E3TimeStamp AS DATE) = '2023-06-05'
GO

SELECT [E3TimeStamp], [MB2.QGFV_A.TR.T_1], [MB2.QGFV_A.TR.T_2]
FROM QGBT_A_SACU
WHERE CAST(E3TimeStamp AS DATE) = '2023-06-05'
GO






SELECT [E3TimeStamp], [MB2.QGFV_B.MED.IB], [MB2.QGFV_B.MED.IC], [MB2.QGFV_B.MED.VA], [MB2.QGFV_B.MED.VB], [MB2.QGFV_B.MED.VC], [MB2.QGFV_B.MED.I_Trif], 
[MB2.QGFV_B.MED.V_Trif], [MB2.QGFV_B.MED.PA], [MB2.QGFV_B.MED.PB], [MB2.QGFV_B.MED.PC], [MB2.QGFV_B.MED.FREQ]
FROM QGBT_B_MED
WHERE CAST(E3TimeStamp AS DATE) = '2023-06-05'
GO


SELECT [E3TimeStamp], [MB2.QGFV_B.DJ.VA], [MB2.QGFV_B.DJ.VB], [MB2.QGFV_B.DJ.VC],[MB2.QGFV_B.DJ.VAB],[MB2.QGFV_B.DJ.VBC],[MB2.QGFV_B.DJ.VCA]
FROM QGBT_B_CAB
WHERE CAST(E3TimeStamp AS DATE) = '2023-06-05'
GO

SELECT [E3TimeStamp], [MB2.QGFV_B.TR.T_1], [MB2.QGFV_B.TR.T_2]
FROM QGBT_B_SACU
WHERE CAST(E3TimeStamp AS DATE) = '2023-06-05'
GO











SELECT [E3TimeStamp], [MB2.QGFV_C.MED.IB], [MB2.QGFV_C.MED.IC], [MB2.QGFV_C.MED.VA], [MB2.QGFV_C.MED.VB], [MB2.QGFV_C.MED.VC], [MB2.QGFV_C.MED.I_Trif], 
[MB2.QGFV_C.MED.V_Trif], [MB2.QGFV_C.MED.PA], [MB2.QGFV_C.MED.PB], [MB2.QGFV_C.MED.PC], [MB2.QGFV_C.MED.FREQ]
FROM QGBT_C_MED
WHERE CAST(E3TimeStamp AS DATE) = '2023-06-05'
GO


SELECT [E3TimeStamp], [MB2.QGFV_C.DJ.VA], [MB2.QGFV_C.DJ.VB], [MB2.QGFV_C.DJ.VC],[MB2.QGFV_C.DJ.VAB],[MB2.QGFV_C.DJ.VBC],[MB2.QGFV_C.DJ.VCA]
FROM QGBT_C_CAB
WHERE CAST(E3TimeStamp AS DATE) = '2023-06-05'
GO

SELECT [E3TimeStamp], [MB2.QGFV_C.TR.T_1], [MB2.QGFV_C.TR.T_2]
FROM QGBT_C_SACU
WHERE CAST(E3TimeStamp AS DATE) = '2023-06-05'
GO